"""Short-lived Bilibili QR login flow for the single-user admin console."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import os
import secrets
import time
from typing import Any

import httpx


_GENERATE_URL = "https://passport.bilibili.com/x/passport-login/web/qrcode/generate"
_POLL_URL = "https://passport.bilibili.com/x/passport-login/web/qrcode/poll"
_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
)


@dataclass
class _PendingQr:
    owner: str
    key: str
    qr_url: str
    expires_at: float


def _netscape_cookie_text(cookies: httpx.Cookies) -> str:
    rows = ["# Netscape HTTP Cookie File", "# Generated by Otomo Bilibili QR login"]
    found_session = False
    for cookie in cookies.jar:
        domain = str(cookie.domain or ".bilibili.com")
        if not domain.lstrip(".").lower().endswith("bilibili.com") or not cookie.value:
            continue
        found_session = found_session or cookie.name == "SESSDATA"
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if cookie.secure else "FALSE"
        expires = int(cookie.expires or 0)
        rows.append(
            "\t".join((domain, include_subdomains, cookie.path or "/", secure, str(expires), cookie.name, cookie.value))
        )
    if not found_session:
        raise RuntimeError("扫码成功，但B站没有返回 SESSDATA；请重试或继续使用 cookies.txt 导入")
    return "\n".join(rows) + "\n"


def _write_cookie_file(path: str, value: str) -> None:
    target = Path(path).resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_name(f".{target.name}.{secrets.token_hex(4)}.tmp")
    temporary.write_text(value, encoding="utf-8")
    try:
        os.chmod(temporary, 0o600)
    except OSError:
        pass
    temporary.replace(target)


class BilibiliQrLoginService:
    def __init__(self, cookie_path: str) -> None:
        self.cookie_path = cookie_path
        self._pending: dict[str, _PendingQr] = {}

    def _cleanup(self) -> None:
        now = time.time()
        self._pending = {
            login_id: pending for login_id, pending in self._pending.items()
            if pending.expires_at > now
        }

    async def start(self, owner: str) -> dict[str, Any]:
        self._cleanup()
        async with httpx.AsyncClient(timeout=10, headers={"User-Agent": _UA}) as client:
            response = await client.get(_GENERATE_URL)
            response.raise_for_status()
            payload = response.json()
        if int(payload.get("code", -1)) != 0:
            raise RuntimeError(str(payload.get("message") or "B站二维码生成失败"))
        data = payload.get("data") or {}
        key = str(data.get("qrcode_key") or "")
        qr_url = str(data.get("url") or "")
        if not key or not qr_url:
            raise RuntimeError("B站二维码响应缺少必要字段")
        login_id = "bqr_" + secrets.token_urlsafe(18).replace("-", "").replace("_", "")
        expires_at = time.time() + 180
        self._pending[login_id] = _PendingQr(owner=owner, key=key, qr_url=qr_url, expires_at=expires_at)
        return {
            "login_id": login_id,
            "qr_url": qr_url,
            "status": "waiting",
            "message": "请使用哔哩哔哩手机客户端扫码",
            "expires_at": datetime.fromtimestamp(expires_at, timezone.utc).isoformat(),
        }

    async def poll(self, owner: str, login_id: str) -> dict[str, Any]:
        self._cleanup()
        pending = self._pending.get(login_id)
        if pending is None or pending.owner != owner:
            return {"status": "expired", "message": "二维码已过期，请重新生成"}
        async with httpx.AsyncClient(
            timeout=10,
            headers={"User-Agent": _UA, "Referer": "https://www.bilibili.com/"},
            follow_redirects=False,
        ) as client:
            response = await client.get(_POLL_URL, params={"qrcode_key": pending.key})
            response.raise_for_status()
            payload = response.json()
        if int(payload.get("code", -1)) != 0:
            raise RuntimeError(str(payload.get("message") or "B站扫码状态读取失败"))
        data = payload.get("data") or {}
        code = int(data.get("code") or 0)
        if code == 0:
            cookie_text = _netscape_cookie_text(response.cookies)
            _write_cookie_file(self.cookie_path, cookie_text)
            self._pending.pop(login_id, None)
            return {"status": "connected", "message": "B站登录态已安全保存到服务器"}
        if code == 86090:
            return {"status": "scanned", "message": "已扫码，请在手机上确认登录"}
        if code == 86101:
            return {"status": "waiting", "message": "等待扫码"}
        if code == 86038:
            self._pending.pop(login_id, None)
            return {"status": "expired", "message": "二维码已过期，请重新生成"}
        return {"status": "waiting", "message": str(data.get("message") or "等待B站确认")}
